<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="featuremodel" nsURI="http://www.example.org/featuremodel" nsPrefix="featuremodel">
  <eClassifiers xsi:type="ecore:EClass" name="FeatureDiagram" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootFeature" lowerBound="1"
        eType="#//RootFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childRelations" upperBound="-1"
        eType="#//ChildRelation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFeature" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AbstractFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" lowerBound="1" eType="#//State"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildRelation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//AbstractFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" lowerBound="1" eType="#//State"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleChildRelation" abstract="true"
      eSuperTypes="#//ChildRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleChildrenRelation" abstract="true"
      eSuperTypes="#//ChildRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
        upperBound="-1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiresConstraint" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExcludesConstraint" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryRelation" eSuperTypes="#//SingleChildRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="OptionalRelation" eSuperTypes="#//SingleChildRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrRelation" eSuperTypes="#//MultipleChildrenRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeRelation" eSuperTypes="#//MultipleChildrenRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metamodel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainPackage" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootFeature" eSuperTypes="#//AbstractFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//AbstractFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" eType="#//Metamodel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulatorcomponent" eType="#//SimulatorComponent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" lowerBound="1" eType="#//State"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatorComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="IN"/>
    <eLiterals name="OUT" value="1"/>
  </eClassifiers>
</ecore:EPackage>
